/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

public class GerenciaEmprestimo extends javax.swing.JFrame {

    public GerenciaEmprestimo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        b_todos = new javax.swing.JButton();
        b_nunca = new javax.swing.JButton();
        b_mais = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Helping Hand");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Gerenciar Empréstimos");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(108, 26, 200, 42));

        b_todos.setBackground(new java.awt.Color(139, 121, 94));
        b_todos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_todos.setForeground(new java.awt.Color(0, 0, 0));
        b_todos.setText("Visualizar todos os empréstimos");
        b_todos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_todos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_todosActionPerformed(evt);
            }
        });
        getContentPane().add(b_todos, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 86, 270, 47));

        b_nunca.setBackground(new java.awt.Color(139, 121, 94));
        b_nunca.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_nunca.setForeground(new java.awt.Color(0, 0, 0));
        b_nunca.setText("Visualizar quem nunca devolveu ferramenta");
        b_nunca.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_nunca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_nuncaActionPerformed(evt);
            }
        });
        getContentPane().add(b_nunca, new org.netbeans.lib.awtextra.AbsoluteConstraints(44, 216, 339, 47));

        b_mais.setBackground(new java.awt.Color(139, 121, 94));
        b_mais.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_mais.setForeground(new java.awt.Color(0, 0, 0));
        b_mais.setText("Visualizar amigo que mais fez empréstimo");
        b_mais.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_mais.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_maisActionPerformed(evt);
            }
        });
        getContentPane().add(b_mais, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 151, 310, 47));

        jPanel1.setBackground(new java.awt.Color(220, 220, 185));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b_todosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_todosActionPerformed
        TodosEmprestimos objeto = new TodosEmprestimos();
        objeto.setVisible(true);
    }//GEN-LAST:event_b_todosActionPerformed

    private void b_maisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_maisActionPerformed
        MaisEmprestimos objeto = new MaisEmprestimos();
        objeto.setVisible(true);
    }//GEN-LAST:event_b_maisActionPerformed

    private void b_nuncaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_nuncaActionPerformed
        NuncaDevolveu objeto = new NuncaDevolveu();
        objeto.setVisible(true);
    }//GEN-LAST:event_b_nuncaActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerenciaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerenciaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerenciaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerenciaEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerenciaEmprestimo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_mais;
    private javax.swing.JButton b_nunca;
    private javax.swing.JButton b_todos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
