/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.AmigoDAO;
import DAO.EmprestimoDAO;
import DAO.FerramentaDAO;
import Model.Amigo;
import Model.Emprestimo;
import Model.Ferramenta;
import java.sql.SQLException;
import java.text.ParseException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class RegistraEmprestimo extends javax.swing.JFrame {

    public RegistraEmprestimo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        c_amigo = new javax.swing.JComboBox();
        c_ferramenta = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        c_ocorreu = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        c_devolucao = new javax.swing.JTextField();
        b_registrar = new javax.swing.JButton();
        b_cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Helping Hand");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Amigo:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 82, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Ferramenta:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(71, 148, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Registrar Empréstimo");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(125, 29, 208, -1));

        jPanel1.setBackground(new java.awt.Color(220, 220, 185));

        c_amigo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        c_amigo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione um amigo" }));
        c_amigo.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                c_amigoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        c_ferramenta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        c_ferramenta.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Selecione uma ferramenta" }));
        c_ferramenta.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                c_ferramentaAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        c_ferramenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                c_ferramentaMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Data que Ocorreu:");

        c_ocorreu.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Data de Devolução:");

        c_devolucao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        b_registrar.setBackground(new java.awt.Color(139, 121, 94));
        b_registrar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_registrar.setForeground(new java.awt.Color(0, 0, 0));
        b_registrar.setText("Registrar");
        b_registrar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_registrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_registrarActionPerformed(evt);
            }
        });

        b_cancelar.setBackground(new java.awt.Color(139, 121, 94));
        b_cancelar.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        b_cancelar.setForeground(new java.awt.Color(0, 0, 0));
        b_cancelar.setText("Cancelar");
        b_cancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(c_devolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(c_ocorreu, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(c_amigo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(c_ferramenta, javax.swing.GroupLayout.Alignment.TRAILING, 0, 322, Short.MAX_VALUE)))
                .addContainerGap(79, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(b_cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addComponent(b_registrar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(114, 114, 114))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addComponent(c_amigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(c_ferramenta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c_ocorreu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(c_devolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(b_registrar)
                    .addComponent(b_cancelar))
                .addContainerGap(39, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 470, 440));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_b_cancelarActionPerformed

    private void b_registrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_registrarActionPerformed
        try {

            // INSTANCIAS     
            AmigoDAO amigoDAO = new AmigoDAO();
            ArrayList<Amigo> amigos = new ArrayList<Amigo>();
            FerramentaDAO ferramentaDAO = new FerramentaDAO();
            EmprestimoDAO emprestimoDAO = new EmprestimoDAO();
            int ID_amigo;

            String nome_amigo = this.c_amigo.getSelectedItem().toString();

            // REGISTRO DO EMPRESTIMO
            Emprestimo emprestimo = new Emprestimo();

            int ID_ferramenta;

            String data_ocorreu = this.c_ocorreu.getText();
            String data_devolucao = this.c_devolucao.getText();
            String ferramenta_marca = this.c_ferramenta.getSelectedItem().toString();
            String[] parts = ferramenta_marca.split(" ");
            String nome_ferramenta = parts[0];
            String marca_ferramenta = parts[1];

            // FORMATANDO DATAS
            DateTimeFormatter format = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            String data_ocorreu_emprestimo = LocalDate.parse(data_ocorreu, format).toString();
            String data_devolucao_emprestimo = LocalDate.parse(data_devolucao, format).toString();

            // VALIDAÇÃO        
            // RETORNANDO AMIGO
            ID_amigo = amigoDAO.BuscaAmigoByNameRetornandoID(nome_amigo);

            // RETORNANDO FERRAMENTA
            ID_ferramenta = ferramentaDAO.buscaFerramentaByNomeMarca(nome_ferramenta, marca_ferramenta).getID_ferramenta();

            //VALIDA SE O USUARIO SELECIONADO POSSUI PENDENCIA, SE SIM ENVIA PARA OUTRA TELA
            try {
                amigos = amigoDAO.visualizar_quem_nunca_devolveu_ferramenta();

                for (int i = 0; i < amigos.size(); i++) {
                    if (amigos.get(i).getNome_amigo() == nome_amigo) {
                        PopUpConfirmar objeto = new PopUpConfirmar(ID_amigo, ID_ferramenta, data_ocorreu_emprestimo, data_devolucao_emprestimo);
                        objeto.setVisible(true);
                    }
                }

            } catch (ParseException ex) {
            }

            // INSERINDO EMRPRESTIMO NO BANCO
            emprestimo.setID_amigo(ID_amigo);
            emprestimo.setID_ferramenta(ID_ferramenta);
            emprestimo.setData_ocorreu(data_ocorreu_emprestimo);
            emprestimo.setData_devolucao(data_devolucao_emprestimo);
            emprestimoDAO.InsertEmprestimoDB(emprestimo);

        } catch (NumberFormatException erro2) {
            JOptionPane.showMessageDialog(null, "Informe um n�mero.");
        } finally{
            JOptionPane.showMessageDialog(null, "Emprestimo realizado com sucesso!!");
        }
    }//GEN-LAST:event_b_registrarActionPerformed

    private void c_amigoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_c_amigoAncestorAdded
        ArrayList<Amigo> amigos = new ArrayList<Amigo>();
        AmigoDAO amigoDAO = new AmigoDAO();

        amigos = amigoDAO.getVisualizaAmigos();

        this.c_amigo.removeAll();

        int i;
        for (i = 0; i < amigos.size(); i++) {
            this.c_amigo.addItem(amigos.get(i).getNome_amigo());
        }
    }//GEN-LAST:event_c_amigoAncestorAdded

    private void c_ferramentaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_c_ferramentaAncestorAdded
        ArrayList<Ferramenta> ferramentas = new ArrayList<Ferramenta>();
        FerramentaDAO ferramentaDAO = new FerramentaDAO();

        ferramentas = ferramentaDAO.visualizaFerramentas();

        this.c_ferramenta.removeAll();

        int i;
        for (i = 0; i < ferramentas.size(); i++) {
            this.c_ferramenta.addItem(ferramentas.get(i).getNome_ferramenta() + " " + ferramentas.get(i).getMarca());
        }
    }//GEN-LAST:event_c_ferramentaAncestorAdded

    private void c_ferramentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_c_ferramentaMouseClicked

    }//GEN-LAST:event_c_ferramentaMouseClicked

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegistraEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegistraEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegistraEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegistraEmprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegistraEmprestimo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_cancelar;
    private javax.swing.JButton b_registrar;
    private javax.swing.JComboBox c_amigo;
    private javax.swing.JTextField c_devolucao;
    private javax.swing.JComboBox c_ferramenta;
    private javax.swing.JTextField c_ocorreu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
