package View;

public class TelaPrincipal extends javax.swing.JFrame {

    public TelaPrincipal() {
        initComponents();
    }     
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jProgressBar1 = new javax.swing.JProgressBar();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        b_cadferramenta = new javax.swing.JButton();
        b_visuferramentas = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        b_cadamigo = new javax.swing.JButton();
        b_visuamigos = new javax.swing.JButton();
        b_regiemprestimo = new javax.swing.JButton();
        b_gerenemprestimos = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Helping Hand");
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(220, 220, 185));
        jPanel1.setToolTipText("");
        jPanel1.setName("Helping Hand"); // NOI18N

        jLabel1.setFont(new java.awt.Font("Microsoft JhengHei", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(64, 43, 21));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Helping Hand");

        b_cadferramenta.setBackground(new java.awt.Color(139, 121, 94));
        b_cadferramenta.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        b_cadferramenta.setForeground(new java.awt.Color(0, 0, 0));
        b_cadferramenta.setText("         Cadastrar Ferramenta");
        b_cadferramenta.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_cadferramenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cadferramentaActionPerformed(evt);
            }
        });

        b_visuferramentas.setBackground(new java.awt.Color(139, 121, 94));
        b_visuferramentas.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        b_visuferramentas.setForeground(new java.awt.Color(0, 0, 0));
        b_visuferramentas.setText("Visualizar Ferramentas              ");
        b_visuferramentas.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_visuferramentas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_visuferramentasActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/aperto-de-mao-de-parceria.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        jLabel2.setFont(new java.awt.Font("Microsoft YaHei", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(64, 43, 21));
        jLabel2.setText("By SevenIT");

        b_cadamigo.setBackground(new java.awt.Color(139, 121, 94));
        b_cadamigo.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        b_cadamigo.setForeground(new java.awt.Color(0, 0, 0));
        b_cadamigo.setText("           Cadastrar Amigo  ");
        b_cadamigo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_cadamigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cadamigoActionPerformed(evt);
            }
        });

        b_visuamigos.setBackground(new java.awt.Color(139, 121, 94));
        b_visuamigos.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        b_visuamigos.setForeground(new java.awt.Color(0, 0, 0));
        b_visuamigos.setText("Visualizar Amigos            ");
        b_visuamigos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_visuamigos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_visuamigosActionPerformed(evt);
            }
        });

        b_regiemprestimo.setBackground(new java.awt.Color(139, 121, 94));
        b_regiemprestimo.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        b_regiemprestimo.setForeground(new java.awt.Color(0, 0, 0));
        b_regiemprestimo.setText("               Registrar Empréstimo");
        b_regiemprestimo.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_regiemprestimo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_regiemprestimoActionPerformed(evt);
            }
        });

        b_gerenemprestimos.setBackground(new java.awt.Color(139, 121, 94));
        b_gerenemprestimos.setFont(new java.awt.Font("Microsoft YaHei", 1, 14)); // NOI18N
        b_gerenemprestimos.setForeground(new java.awt.Color(0, 0, 0));
        b_gerenemprestimos.setText("Gerenciar Empréstimos      ");
        b_gerenemprestimos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_gerenemprestimos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_gerenemprestimosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_visuferramentas, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_gerenemprestimos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(210, 210, 210))
                    .addComponent(b_visuamigos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(b_cadferramenta, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_cadamigo, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(b_regiemprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 446, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(112, 112, 112)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(173, 173, 173)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b_cadferramenta, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(b_visuferramentas, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(b_cadamigo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(b_visuamigos, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(b_regiemprestimo, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(b_gerenemprestimos, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.getAccessibleContext().setAccessibleName("Helping Hand");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b_visuferramentasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_visuferramentasActionPerformed
        VisualizaFerramenta objeto = new VisualizaFerramenta();
        objeto.setVisible(true);
    }//GEN-LAST:event_b_visuferramentasActionPerformed

    private void b_cadferramentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cadferramentaActionPerformed
        CadastroFerramenta objeto = new CadastroFerramenta();
        objeto.setVisible(true);
    }//GEN-LAST:event_b_cadferramentaActionPerformed

    private void b_cadamigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cadamigoActionPerformed
        CadastroAmigo objeto = new CadastroAmigo();
        objeto.setVisible(true);
    }//GEN-LAST:event_b_cadamigoActionPerformed

    private void b_visuamigosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_visuamigosActionPerformed
        VisualizaAmigo objeto = new VisualizaAmigo();
        objeto.setVisible(true);
    }//GEN-LAST:event_b_visuamigosActionPerformed

    private void b_regiemprestimoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_regiemprestimoActionPerformed
        RegistraEmprestimo objeto = new RegistraEmprestimo();
        objeto.setVisible(true);
    }//GEN-LAST:event_b_regiemprestimoActionPerformed

    private void b_gerenemprestimosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_gerenemprestimosActionPerformed
        GerenciaEmprestimo objeto = new GerenciaEmprestimo();
        objeto.setVisible(true);
    }//GEN-LAST:event_b_gerenemprestimosActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_cadamigo;
    private javax.swing.JButton b_cadferramenta;
    private javax.swing.JButton b_gerenemprestimos;
    private javax.swing.JButton b_regiemprestimo;
    private javax.swing.JButton b_visuamigos;
    private javax.swing.JButton b_visuferramentas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    // End of variables declaration//GEN-END:variables
}
