package View;

import DAO.AmigoDAO;
import DAO.FerramentaDAO;
import Model.Amigo;
import Model.Emprestimo;
import Model.Ferramenta;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class TodosEmprestimos extends javax.swing.JFrame {

    private Emprestimo objEmprestimo;

    public TodosEmprestimos() {
        initComponents();
        this.objEmprestimo = new Emprestimo(); // carrega objeto Emprestimo
        this.carregaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_emprestimo = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        c_data_devolucao = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        c_status = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Helping Hand");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(220, 220, 185));

        tabela_emprestimo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Amigo", "Ferramenta", "Marca", "Data que Ocorreu", "Data de Devolução", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela_emprestimo.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tabela_emprestimoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tabela_emprestimo.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tabela_emprestimoFocusGained(evt);
            }
        });
        tabela_emprestimo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabela_emprestimoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela_emprestimo);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Todos os Empréstimos:");

        jButton1.setBackground(new java.awt.Color(139, 121, 94));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Cancelar");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(139, 121, 94));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Alterar");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(139, 121, 94));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Apagar");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Data de Devolução:");

        c_data_devolucao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Status:");

        c_status.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        c_status.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-", "ATIVO", "NÃO ATIVO" }));
        c_status.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                c_statusComponentAdded(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 768, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(274, 274, 274)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(c_status, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(c_data_devolucao, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(79, 79, 79)
                                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(16, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel7)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(c_data_devolucao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(c_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap(172, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 520));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void tabela_emprestimoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabela_emprestimoAncestorAdded

    }//GEN-LAST:event_tabela_emprestimoAncestorAdded

    private void tabela_emprestimoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela_emprestimoMouseClicked
        if (this.tabela_emprestimo.getSelectedRow() != -1) {

            String ID_emprestimo = this.tabela_emprestimo.getValueAt(this.tabela_emprestimo.getSelectedRow(), 0).toString();
            String amigo = this.tabela_emprestimo.getValueAt(this.tabela_emprestimo.getSelectedRow(), 1).toString();
            String ferramenta = this.tabela_emprestimo.getValueAt(this.tabela_emprestimo.getSelectedRow(), 2).toString();
            String marca = this.tabela_emprestimo.getValueAt(this.tabela_emprestimo.getSelectedRow(), 3).toString();
            String data_ocorreu = this.tabela_emprestimo.getValueAt(this.tabela_emprestimo.getSelectedRow(), 4).toString();
            String data_devolucao = this.tabela_emprestimo.getValueAt(this.tabela_emprestimo.getSelectedRow(), 5).toString();
            String status = this.tabela_emprestimo.getValueAt(this.tabela_emprestimo.getSelectedRow(), 6).toString();
            this.c_data_devolucao.setText(data_devolucao);
            
            if(status == "true"){
                this.c_status.setSelectedIndex(1);
            }else if(status == "false"){
                this.c_status.setSelectedIndex(2);
            }      
        }
    }//GEN-LAST:event_tabela_emprestimoMouseClicked

    private void c_statusComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_c_statusComponentAdded

    }//GEN-LAST:event_c_statusComponentAdded

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        AmigoDAO amigoDAO = new AmigoDAO();
        int ID_amigo;
        FerramentaDAO ferramentaDAO = new FerramentaDAO();
        int ID_ferramenta;

        try {
            // recebendo e validando dados da interface gr�fica.
            int ID_emprestimo = 0;
            String nome_amigo = this.tabela_emprestimo.getValueAt(this.tabela_emprestimo.getSelectedRow(), 1).toString();
            String nome_ferramenta = this.tabela_emprestimo.getValueAt(this.tabela_emprestimo.getSelectedRow(), 2).toString();
            String marca = this.tabela_emprestimo.getValueAt(this.tabela_emprestimo.getSelectedRow(), 3).toString();
            String data_ocorreu = this.tabela_emprestimo.getValueAt(this.tabela_emprestimo.getSelectedRow(), 4).toString();
            String data_devolucao = this.c_data_devolucao.getText();
            int campo_status = this.c_status.getSelectedIndex();
            
            Boolean status_emprestimo = true;
            
            if(campo_status == 1){
                status_emprestimo = true;            
            }else if(campo_status == 2){
                status_emprestimo = false;
            }
            

            //VALIDACAO
            if (this.tabela_emprestimo.getSelectedRow() == -1) {
                throw new Mensagens("Primeiro Selecione um emprestimo para Alterar");
            } else {
                ID_emprestimo = Integer.parseInt(this.tabela_emprestimo.getValueAt(this.tabela_emprestimo.getSelectedRow(), 0).toString());
            }

            //PEGANDO AMIGO
            ID_amigo = amigoDAO.BuscaAmigoByNameRetornandoID(data_devolucao);

            //PEGANDO FERRAMENTA
            ID_ferramenta = ferramentaDAO.buscaFerramentaByNomeMarca(nome_ferramenta, marca).getID_ferramenta(); 
            
            // envia os dados para o emprestimo processar
            if (this.objEmprestimo.UpdateEmprestimoBD(ID_emprestimo, ID_amigo, ID_ferramenta, data_ocorreu, data_devolucao, status_emprestimo)) {             
                // limpa os campos
                this.c_data_devolucao.setText("");
                this.c_status.setSelectedIndex(0);
                JOptionPane.showMessageDialog(rootPane, "Emprestimo Alterado com Sucesso!");

            }
        } catch (Mensagens erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        } catch (NumberFormatException erro2) {
            JOptionPane.showMessageDialog(null, "Informe um n�mero.");
        } finally {
            carregaTabela(); // atualiza a tabela.
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tabela_emprestimoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tabela_emprestimoFocusGained
        
    }//GEN-LAST:event_tabela_emprestimoFocusGained

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TodosEmprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TodosEmprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TodosEmprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TodosEmprestimos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TodosEmprestimos().setVisible(true);
            }
        });
    }

    @SuppressWarnings("unchecked")
    private void carregaTabela() {
        AmigoDAO amigoDAO = new AmigoDAO();
        Amigo amigo = new Amigo();
        FerramentaDAO ferramentaDAO = new FerramentaDAO();
        Ferramenta ferramenta = new Ferramenta();

        DefaultTableModel modelo = (DefaultTableModel) this.tabela_emprestimo.getModel();
        modelo.setNumRows(0);

        ArrayList<Emprestimo> emprestimos = new ArrayList<Emprestimo>();
        emprestimos = objEmprestimo.visualizaEmprestimos();

        for (int i = 0; i < emprestimos.size(); i++) {
            amigo = amigoDAO.carregaAmigo(i + 1);
            ferramenta = ferramentaDAO.carregaFerramenta(i + 1);

            modelo.addRow(new Object[]{
                emprestimos.get(i).getID_emprestimo(),
                amigo.getNome_amigo(),
                ferramenta.getNome_ferramenta(),
                ferramenta.getMarca(),
                emprestimos.get(i).getData_ocorreu(),
                emprestimos.get(i).getData_devolucao(),
                emprestimos.get(i).getStatus_emprestimo(),
            });
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField c_data_devolucao;
    private javax.swing.JComboBox<String> c_status;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela_emprestimo;
    // End of variables declaration//GEN-END:variables
}
