package View;

import Model.Amigo;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


public class VisualizaAmigo extends javax.swing.JFrame {

    private Amigo objamigo; // cria o v�nculo com o objeto de amigo

    public VisualizaAmigo() {
        initComponents();
        this.objamigo = new Amigo(); // carrega objeto de amigo
        this.carregaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_amigo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        c_amigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        c_email = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        c_telefone = new javax.swing.JTextField();
        b_cancelar = new javax.swing.JButton();
        b_alterar = new javax.swing.JButton();
        b_apagar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Helping Hand");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabela_amigo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Amigo", "E-mail", "Telefone"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela_amigo.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tabela_amigoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        tabela_amigo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabela_amigoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela_amigo);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(26, 83, -1, 137));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Nome:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 257, 40, -1));

        c_amigo.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(c_amigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 254, 233, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("E-mail:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 297, 40, -1));

        c_email.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(c_email, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 294, 233, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Telefone:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 337, 53, -1));

        c_telefone.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(c_telefone, new org.netbeans.lib.awtextra.AbsoluteConstraints(172, 334, 233, -1));

        b_cancelar.setBackground(new java.awt.Color(139, 121, 94));
        b_cancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_cancelar.setForeground(new java.awt.Color(0, 0, 0));
        b_cancelar.setText("Cancelar");
        b_cancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(b_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 397, 80, -1));

        b_alterar.setBackground(new java.awt.Color(139, 121, 94));
        b_alterar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_alterar.setForeground(new java.awt.Color(0, 0, 0));
        b_alterar.setText("Alterar");
        b_alterar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_alterarActionPerformed(evt);
            }
        });
        getContentPane().add(b_alterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(217, 397, 70, -1));

        b_apagar.setBackground(new java.awt.Color(139, 121, 94));
        b_apagar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_apagar.setForeground(new java.awt.Color(0, 0, 0));
        b_apagar.setText("Apagar");
        b_apagar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_apagarActionPerformed(evt);
            }
        });
        getContentPane().add(b_apagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(333, 397, 70, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Visualizar Amigos");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(161, 27, 160, -1));

        jPanel1.setBackground(new java.awt.Color(220, 220, 185));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tabela_amigoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela_amigoMouseClicked
        if (this.tabela_amigo.getSelectedRow() != -1) {
            
            String nome_amigo = this.tabela_amigo.getValueAt(this.tabela_amigo.getSelectedRow(), 1).toString();
            String email = this.tabela_amigo.getValueAt(this.tabela_amigo.getSelectedRow(), 2).toString();
            String telefone = this.tabela_amigo.getValueAt(this.tabela_amigo.getSelectedRow(), 3).toString();
            
            this.c_amigo.setText(nome_amigo);
            this.c_email.setText(email);
            this.c_telefone.setText(telefone);
        }
    }//GEN-LAST:event_tabela_amigoMouseClicked

    private void b_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_b_cancelarActionPerformed

    private void b_apagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_apagarActionPerformed
        try{
            // validando dados da interface gr�fica.
            int ID_amigo = 0;
            if (this.tabela_amigo.getSelectedRow() == -1) {
                throw new Mensagens("Primeiro Selecione um Amigo para APAGAR");
            } else {
                ID_amigo = Integer.parseInt(this.tabela_amigo.getValueAt(this.tabela_amigo.getSelectedRow(), 0).toString());
            }

            // retorna 0 -> primeiro bot�o | 1 -> segundo bot�o | 2 -> terceiro bot�o
            int resposta_usuario = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja APAGAR este Amigo ?");

            if (resposta_usuario == 0) {// clicou em SIM

                // envia os dados para o Amigo processar
                if (this.objamigo.DeleteAmigoBD(ID_amigo)) {

                    // limpa os campos
                    this.c_amigo.setText("");
                    this.c_email.setText("");
                    this.c_telefone.setText("");
                    JOptionPane.showMessageDialog(rootPane, "Amigo Apagado com Sucesso!");

                }

            }


        } catch (Mensagens erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        } finally {
            // atualiza a tabela.
            carregaTabela();
        }
    }

    @SuppressWarnings("unchecked")
    private void carregaTabela() {
        DefaultTableModel modelo = (DefaultTableModel) this.tabela_amigo.getModel();
        modelo.setNumRows(0);

        ArrayList<Amigo> visualizaamigos = new ArrayList<>();
        visualizaamigos = objamigo.getVisualizaAmigos();

        for (Amigo a : visualizaamigos) {
            modelo.addRow(new Object[]{
                a.getID_amigo(),
                a.getNome_amigo(),
                a.getEmail(),
                a.getTelefone(),
            });
        }
    }//GEN-LAST:event_b_apagarActionPerformed

    private void b_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_alterarActionPerformed
        try {
            // recebendo e validando dados da interface gr�fica.
            int ID_amigo = 0;
            String nome_amigo = "";
            String email = "";
            String telefone = "";

            if (this.c_amigo.getText().length() < 2) {
                throw new Mensagens("Nome deve conter ao menos 2 caracteres.");
            } else {
                nome_amigo = this.c_amigo.getText();
            }

            if (this.c_email.getText().length() < 2) {
                throw new Mensagens("E-mail deve conter ao menos 2 caracteres.");
            } else {
                email = this.c_email.getText();
            }

            if (this.c_telefone.getText().length() <= 0) {
                throw new Mensagens("Telefone deve conter ao menos 9 dígitos e o DDD");
            } else {
                telefone = this.c_telefone.getText();
            }

            if (this.tabela_amigo.getSelectedRow() == -1) {
                throw new Mensagens("Primeiro Selecione um Amigo para Alterar");
            } else {
                ID_amigo = Integer.parseInt(this.tabela_amigo.getValueAt(this.tabela_amigo.getSelectedRow(), 0).toString());
            }

            // envia os dados para o Aluno processar
            if (this.objamigo.UpdateAmigoBD(ID_amigo, nome_amigo, telefone, email)) {

                // limpa os campos
                this.c_amigo.setText("");
                this.c_email.setText("");
                this.c_telefone.setText("");
                JOptionPane.showMessageDialog(rootPane, "Amigo Alterado com Sucesso!");

            }
            System.out.println(this.objamigo.getVisualizaAmigos().toString());
        } catch (Mensagens erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        } catch (NumberFormatException erro2) {
            JOptionPane.showMessageDialog(null, "Informe um n�mero.");
        } finally {
            carregaTabela(); // atualiza a tabela.
        }              
    }//GEN-LAST:event_b_alterarActionPerformed

    private void tabela_amigoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabela_amigoAncestorAdded

    }//GEN-LAST:event_tabela_amigoAncestorAdded
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisualizaAmigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisualizaAmigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisualizaAmigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualizaAmigo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisualizaAmigo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_alterar;
    private javax.swing.JButton b_apagar;
    private javax.swing.JButton b_cancelar;
    private javax.swing.JTextField c_amigo;
    private javax.swing.JTextField c_email;
    private javax.swing.JTextField c_telefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela_amigo;
    // End of variables declaration//GEN-END:variables
}
