/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import DAO.FerramentaDAO;
import Model.Ferramenta;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Beatriz
 */
public class VisualizaFerramenta extends javax.swing.JFrame {

    private Ferramenta objferramenta; // cria o v�nculo com o objaluno

    public VisualizaFerramenta() {
        initComponents();
        this.objferramenta = new Ferramenta(); // carrega objaluno de aluno
        this.carregaTabela();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_ferramenta = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        c_ferramenta = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        c_marca = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        c_custoAquisicao = new javax.swing.JTextField();
        b_cancelar = new javax.swing.JButton();
        b_alterar = new javax.swing.JButton();
        b_apagar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        c_totalGasto = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Helping Hand");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabela_ferramenta.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Ferramenta", "Marca", "Custo de Aquisição (R$)"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabela_ferramenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabela_ferramentaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabela_ferramenta);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(18, 72, 544, 171));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Total Gasto (R$):");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 255, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Ferramenta:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(111, 314, 78, -1));

        c_ferramenta.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(c_ferramenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 311, 254, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 0, 0));
        jLabel3.setText("Marca:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 354, 50, -1));

        c_marca.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(c_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 351, 254, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 0));
        jLabel4.setText("Custo de Aquisição (R$):");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(47, 394, 142, -1));

        c_custoAquisicao.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        getContentPane().add(c_custoAquisicao, new org.netbeans.lib.awtextra.AbsoluteConstraints(194, 391, 254, -1));

        b_cancelar.setBackground(new java.awt.Color(139, 121, 94));
        b_cancelar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_cancelar.setForeground(new java.awt.Color(0, 0, 0));
        b_cancelar.setText("Cancelar");
        b_cancelar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_cancelarActionPerformed(evt);
            }
        });
        getContentPane().add(b_cancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 455, 72, -1));

        b_alterar.setBackground(new java.awt.Color(139, 121, 94));
        b_alterar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_alterar.setForeground(new java.awt.Color(0, 0, 0));
        b_alterar.setText("Alterar");
        b_alterar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_alterarActionPerformed(evt);
            }
        });
        getContentPane().add(b_alterar, new org.netbeans.lib.awtextra.AbsoluteConstraints(265, 455, 65, -1));

        b_apagar.setBackground(new java.awt.Color(139, 121, 94));
        b_apagar.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        b_apagar.setForeground(new java.awt.Color(0, 0, 0));
        b_apagar.setText("Apagar");
        b_apagar.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        b_apagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b_apagarActionPerformed(evt);
            }
        });
        getContentPane().add(b_apagar, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 455, 64, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Visualizar Ferramentas ");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(195, 21, -1, -1));

        jPanel1.setBackground(new java.awt.Color(220, 220, 185));

        c_totalGasto.setEditable(false);
        c_totalGasto.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        c_totalGasto.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                c_totalGastoAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(255, Short.MAX_VALUE)
                .addComponent(c_totalGasto, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(184, 184, 184))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(255, Short.MAX_VALUE)
                .addComponent(c_totalGasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(223, 223, 223))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void b_cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_cancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_b_cancelarActionPerformed

    private void b_alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_alterarActionPerformed
        try {
            // recebendo e validando dados da interface gr�fica.
            int ID_ferramenta = 0;
            String nome_ferramenta = "";
            String marca = "";
            double custo_aquisicao = 0.0;

            if (this.c_ferramenta.getText().length() < 2) {
                throw new Mensagens("Ferramenta deve conter ao menos 2 caracteres.");
            } else {
                nome_ferramenta = this.c_ferramenta.getText();
            }

            if (this.c_marca.getText().length() < 2) {
                throw new Mensagens("Marca deve conter ao menos 2 caracteres.");
            } else {
                marca = this.c_marca.getText();
            }

            if (this.c_custoAquisicao.getText().length() <= 0) {
                throw new Mensagens("Custo de Aquisição deve ser n�mero e maior que zero.");
            } else {
                custo_aquisicao = Double.parseDouble(this.c_custoAquisicao.getText());
            }

            if (this.tabela_ferramenta.getSelectedRow() == -1) {
                throw new Mensagens("Primeiro Selecione uma Ferramenta para Alterar");
            } else {
                ID_ferramenta = Integer.parseInt(this.tabela_ferramenta.getValueAt(this.tabela_ferramenta.getSelectedRow(), 0).toString());
            }

            // envia os dados para a Ferramenta processar
            if (this.objferramenta.UpdateFerramentaBD(ID_ferramenta, nome_ferramenta, marca, custo_aquisicao)) {

                // limpa os campos
                this.c_ferramenta.setText("");
                this.c_marca.setText("");
                this.c_custoAquisicao.setText("");
                JOptionPane.showMessageDialog(rootPane, "Ferramenta Alterada com Sucesso!");

            }
            System.out.println(this.objferramenta.getVisualizaFerramentas().toString());
        } catch (Mensagens erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        } catch (NumberFormatException erro2) {
            JOptionPane.showMessageDialog(null, "Informe um n�mero.");
        } finally {
            carregaTabela(); // atualiza a tabela.
            FerramentaDAO ferramentaDAO = new FerramentaDAO();
            this.c_totalGasto.setText(ferramentaDAO.VisualizaValorFerramentas());
        }
    }//GEN-LAST:event_b_alterarActionPerformed

    private void b_apagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b_apagarActionPerformed
        try {
            // validando dados da interface gr�fica.
            int ID_ferramenta = 0;
            if (this.tabela_ferramenta.getSelectedRow() == -1) {
                throw new Mensagens("Primeiro Selecione uma Ferramenta para APAGAR");
            } else {
                ID_ferramenta = Integer.parseInt(this.tabela_ferramenta.getValueAt(this.tabela_ferramenta.getSelectedRow(), 0).toString());
            }

            // retorna 0 -> primeiro bot�o | 1 -> segundo bot�o | 2 -> terceiro bot�o
            int resposta_usuario = JOptionPane.showConfirmDialog(null, "Tem certeza que deseja APAGAR esta Ferramenta ?");

            if (resposta_usuario == 0) {// clicou em SIM

                // envia os dados para a Ferramenta processar
                if (this.objferramenta.DeleteFerramentaBD(ID_ferramenta)) {

                    // limpa os campos
                    this.c_ferramenta.setText("");
                    this.c_marca.setText("");
                    this.c_custoAquisicao.setText("");
                    JOptionPane.showMessageDialog(rootPane, "Ferramenta Apagada com Sucesso!");

                }

            }

        } catch (Mensagens erro) {
            JOptionPane.showMessageDialog(null, erro.getMessage());
        } finally {
            // atualiza a tabela.
            carregaTabela();
            FerramentaDAO ferramentaDAO = new FerramentaDAO();
            this.c_totalGasto.setText(ferramentaDAO.VisualizaValorFerramentas());
        }
    }//GEN-LAST:event_b_apagarActionPerformed

    private void tabela_ferramentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabela_ferramentaMouseClicked
        if (this.tabela_ferramenta.getSelectedRow() != -1) {

            String nome_ferramenta = this.tabela_ferramenta.getValueAt(this.tabela_ferramenta.getSelectedRow(), 1).toString();
            String marca = this.tabela_ferramenta.getValueAt(this.tabela_ferramenta.getSelectedRow(), 2).toString();
            String custo_aquisicao = this.tabela_ferramenta.getValueAt(this.tabela_ferramenta.getSelectedRow(), 3).toString();

            this.c_ferramenta.setText(nome_ferramenta);
            this.c_marca.setText(marca);
            this.c_custoAquisicao.setText(custo_aquisicao);
        }
    }//GEN-LAST:event_tabela_ferramentaMouseClicked

    private void c_totalGastoAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_c_totalGastoAncestorAdded
        FerramentaDAO ferramentaDAO = new FerramentaDAO();
        this.c_totalGasto.setText(ferramentaDAO.VisualizaValorFerramentas());
    }//GEN-LAST:event_c_totalGastoAncestorAdded

    @SuppressWarnings("unchecked")
    private void carregaTabela() {
        DefaultTableModel modelo = (DefaultTableModel) this.tabela_ferramenta.getModel();
        modelo.setNumRows(0);

        ArrayList<Ferramenta> visualizaferramentas = new ArrayList<>();
        visualizaferramentas = objferramenta.getVisualizaFerramentas();

        for (Ferramenta a : visualizaferramentas) {
            modelo.addRow(new Object[]{
                a.getID_ferramenta(),
                a.getNome_ferramenta(),
                a.getMarca(),
                a.getCusto_aquisicao(),});
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisualizaFerramenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisualizaFerramenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisualizaFerramenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualizaFerramenta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisualizaFerramenta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b_alterar;
    private javax.swing.JButton b_apagar;
    private javax.swing.JButton b_cancelar;
    private javax.swing.JTextField c_custoAquisicao;
    private javax.swing.JTextField c_ferramenta;
    private javax.swing.JTextField c_marca;
    private javax.swing.JTextField c_totalGasto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabela_ferramenta;
    // End of variables declaration//GEN-END:variables
}
